export const REQUEST_RECIPES    = 'REQUEST_RECIPES';
export const SELECT_CATEGORY    = 'SELECT_CATEGORY';
export const FAILED_REQUEST     = 'FAILED_REQUEST';
export const SUCCESSFUL_REQUEST = 'SUCCESSFUL_REQUEST';