export const ADD_RECIPE = 'ADD_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const UPDATE_RECIPE_NAME = 'UPDATE_RECIPE_NAME';
export const UPDATE_RECIPE_DIRECTIONS = 'UPDATE_RECIPE_DIRECTIONS';
export const UPDATE_RECIPE_INGREDIENTS = 'UPDATE_RECIPE_INGREDIENTS';
export const BUILD_LIST = 'BUILD_LIST';

